### ISSUE TITLE
Can't access the Targets dropdown in AppCode 2018.3 EAP

### ISSUE THREAD

**Issue by mark-anders** [mjbeauregard/appcode-scheme-selector#2]
With AppCode 2018.3 EAP, I can no longer access the target selector dropdown. Doing so results in a crash with the following stack trace.  

This has worked without issue for years. I hope you can fix it or that JetBrains does, as I love this plugin and would be lost without it!

```
java.lang.NoSuchMethodError: com.intellij.execution.RunManagerEx.getConfigurationFactories()[Lcom/intellij/execution/configurations/ConfigurationType;
	at com.insightfulminds.appcode.schemeselector.AppCode.getAvailableTargets(AppCode.java:78)
	at com.insightfulminds.appcode.schemeselector.TargetComboBoxAction.createPopupActionGroup(TargetComboBoxAction.java:23)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createPopupActionGroup(ComboBoxAction.java:118)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction.createActionPopup(ComboBoxAction.java:76)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction.access$000(ComboBoxAction.java:37)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.createPopup(ComboBoxAction.java:213)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.showPopup(ComboBoxAction.java:204)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.lambda$fireActionPerformed$0(ComboBoxAction.java:177)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3135)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:176)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:125)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton.fireActionPerformed(ComboBoxAction.java:177)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton$1.mousePressed(ComboBoxAction.java:157)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6545)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.r(IdeEventQueue.java:663)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mjbeauregard** [comment]
Thanks for reporting this issue (as well as logging an issue with Jetbrains - https://youtrack.jetbrains.com/issue/OC-17783).

I tested with the new EAP and can reproduce the problem exactly as you described, but so far I don't see what the problem is. I've commented on the linked JB issue and hopefully they will respond with something that might point me in the right direction.

**Comment by mjbeauregard** [comment]
@mark-anders I have fixed and uploaded a new version of the plugin. It is now waiting for Jetbrains approval. Hopefully it is available for update within AppCode soon. Thanks again for reporting this issue.

**Comment by mark-anders** [comment]
@mjbeauregard - you're welcome! And thank you again for a great plugin. I really depend on it!
